{% set name = "lalmetaio" %}
{% set version = "1.4.0" %}
{% set sha256 = "da06bc6a023e3edcc409d303ef576948d0a3c5103afaaaa748f33346b74daaa8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - make
    - {{ compiler('c') }}
  host:
    - swig >=3.0.7
    - gsl
    - metaio
    - lal >=6.19.0

outputs:
  - name: lalmetaio
    script: install-c.sh
    requirements:
      host:
        - {{ compiler('c') }}
        - make
        - swig >=3.0.7
        - gsl
        - metaio
        - lal >=6.19.0
      run:
        - gsl
        - metaio
        - lal >=6.19.0
    test:
      commands:
        - lalmetaio_version --verbose
    about:
      home: https://wiki.ligo.org/DASWG/LALSuite
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm MetaIO Library
      description: |
        The LSC Algorithm MetaIO Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL MetaIO library.
  - name: python-lalmetaio
    script: install-python.sh
    requirements:
      host:
        - {{ compiler('c') }}
        - make
        - pkg-config
        - swig >=3.0.7
        - {{ pin_subpackage('lalmetaio', exact=True) }}
        - python
        - numpy
      run:
        - {{ pin_subpackage('lalmetaio', exact=True) }}
        - python
        - {{ pin_compatible('numpy') }}
        - python-lal >=6.19.0
    test:
      imports:
        - lalmetaio
    about:
      home: https://wiki.ligo.org/DASWG/LALSuite
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm MetaIO Library
      description: |
        The LSC Algorithm MetaIO Library for gravitational wave data analysis.
        This package contains the python bindings.

about:
  home: https://wiki.ligo.org/DASWG/LALSuite
  license: GPLv3
  license_family: GPL
  summary: LSC Algorithm Frame Library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
