{% set name = "lalmetaio" %}
{% set version = "1.5.0" %}
{% set sha256 = "9571ed6e65463188ce4a1030e6be45b1ce44f76c2c965a4b1e615a68c4efdd03" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
    - swig >=3.0.7
  host:
    - gsl
    - metaio
    - lal >=6.19.0

outputs:
  - name: lalmetaio
    script: install-c.sh
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config
        - swig >=3.0.7
      host:
        - gsl
        - metaio
        - lal >=6.19.0
      run:
        - gsl
        - metaio
        - lal >=6.19.0
    test:
      commands:
        - lalmetaio_version --verbose
    about:
      home: https://wiki.ligo.org/Computing/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalmetaio/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm MetaIO Library
      description: |
        The LSC Algorithm MetaIO Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL MetaIO library.
  - name: python-lalmetaio
    script: install-python.sh
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('c') }}
        - pkg-config
        - make
        - swig >=3.0.7
      host:
        - {{ pin_subpackage('lalmetaio', exact=True) }}
        - python
        - numpy
      run:
        - {{ pin_subpackage('lalmetaio', exact=True) }}
        - python
        - {{ pin_compatible('numpy') }}
        - python-lal >=6.19.0
    test:
      imports:
        - lalmetaio
    about:
      home: https://wiki.ligo.org/Computing/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalmetaio/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm MetaIO Library
      description: |
        The LSC Algorithm MetaIO Library for gravitational wave data analysis.
        This package contains the python bindings.

about:
  home: https://wiki.ligo.org/DASWG/LALSuite
  license: GPLv3
  license_family: GPL
  summary: LSC Algorithm MetaIO Library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
