{% set name = "lalmetaio" %}
{% set version = "1.5.0" %}
{% set sha256 = "9571ed6e65463188ce4a1030e6be45b1ce44f76c2c965a4b1e615a68c4efdd03" %}

# dependencies
{% set lal_version = "6.19.2" %}
{% set swig_version = "3.0.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
    - swig >={{ swig_version }}
  host:
    - gsl
    - lal >={{ lal_version }}
    - metaio
  run:
    - gsl
    - lal >={{ lal_version }}
    - metaio
test:
  commands:
    - lalmetaio_version --verbose

outputs:
  - name: lalmetaio

  - name: python-lalmetaio
    script: install-python.sh
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config
        - swig >={{ swig_version }}
      host:
        - {{ pin_subpackage('lalmetaio', exact=True) }}
        - numpy
        - python
      run:
        - {{ pin_subpackage('lalmetaio', exact=True) }}
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
    test:
      imports:
        - lalmetaio
    about:
      home: https://wiki.ligo.org/Computing/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalmetaio/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm MetaIO Library
      description: |
        The LSC Algorithm MetaIO Library for gravitational wave data analysis.
        This package contains the python bindings.

about:
  home: https://wiki.ligo.org/Computing/DASWG/LALSuite
  doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalmetaio/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm MetaIO Library
  description: |
    The LSC Algorithm MetaIO Library for gravitational wave data analysis.
    This package contains the shared-object libraries needed to run
    applications that use the LAL MetaIO library.  If you want to install
    the Python bindings, please install the associated python-lalmetaio
    package.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
