{% set name = "lalmetaio" %}
{% set version = "4.0.3" %}

# dependencies
{% set lal_version = "7.4.0" %}
{% set metaio_version = "8.4.0" %}
{% set swig_version = "3.0.10" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: ec1aa081e913007ad624ab56bdaabb6f9bbf0ecd83e2d7c3ad51fa65afafdf7a

build:
  error_overlinking: true
  error_overdepending: true
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - help2man >=1.37
    - make
    - pkg-config >=0.18.0
    - swig >={{ swig_version }}
  host:
    - liblal >={{ lal_version }}
    - libmetaio >={{ metaio_version }}

outputs:
  - name: liblalmetaio
    script: install-lib.sh
    build:
      error_overdepending: true
      error_overlinking: true
      run_exports:
        - {{ pin_subpackage("liblalmetaio", max_pin="x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make  # [not win]
        - swig >={{ swig_version }}
      host:
        - liblal >={{ lal_version }}
        - libmetaio >={{ metaio_version }}
      run:
        - liblal >={{ lal_version }}
        - libmetaio >={{ metaio_version }}
      run_constrained:
        - lalmetaio >=2.0.1
        - python-lalmetaio >=2.0.1
    test:
      requires:
        - pkg-config
      commands:
        # check library
        - test -f ${PREFIX}/lib/liblalmetaio${SHLIB_EXT}  # [unix]
        # check pkg-config
        - pkg-config --print-errors --exact-version "${PKG_VERSION}" lalmetaio
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalmetaio/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm MetaIO Library shared object libraries
      description: |
        The LSC Algorithm MetaIO Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL MetaIO library.

  - name: python-lalmetaio
    script: build-python.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        - numpy
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - help2man >=1.37
        - make
        - pkg-config >=0.18.0
        - swig >={{ swig_version }}
        # extras for cross-compiling with python:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
      host:
        - {{ pin_subpackage('liblalmetaio', exact=True) }}
        - numpy
        - python
      run:
        - {{ pin_subpackage('liblalmetaio', exact=True) }}
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
    test:
      requires:
        - pytest >=4.0.0a0
      source_files:
        - test/python
      commands:
        - python -m pytest -ra -v test/python
      imports:
        - lalmetaio
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalmetaio/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm MetaIO Library
      description: |
        The LSC Algorithm MetaIO Library for gravitational wave data analysis.
        This package contains the Python bindings of the LALMetaIO C libraries
        and additional Python modules.

        Note: this package only provides the importable Python libraries.
        All command-line interfaces, scripts, and executables are
        part of the `lalmetaio` package.

  - name: lalmetaio
    script: install-bin.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - help2man >=1.37
        - make
        - sed
      host:
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalmetaio', exact=True) }}
        - python
      run:
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalmetaio', exact=True) }}
        - python
        - {{ pin_subpackage('python-lalmetaio', exact=True) }}
    test:
      commands:
        - lalmetaio_version --verbose
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalmetaio/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm MetaIO Library
      description: |
        The LSC Algorithm MetaIO Library for gravitational wave data analysis.

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalmetaio/
  dev_url: https://git.ligo.org/lscsoft/lalsuite.git
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm MetaIO Library
  description: |
    The LSC Algorithm MetaIO Library for gravitational wave data analysis.

extra:
  feedstock-name: lalmetaio
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
