{% set name = "lalmetaio" %}
{% set version = "2.0.1" %}
{% set sha256 = "1f222f6b6b90d037ebe7d3b352b82b0714758a31731f428ee2373cbe25d24abf" %}

# dependencies
{% set lal_version = "7.1.0" %}
{% set metaio_version = "8.4.0" %}
{% set swig_version = "3.0.10" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  error_overlinking: true
  error_overdepending: true
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - help2man >=1.37
    - make
    - pkg-config >=0.18.0
    - swig >={{ swig_version }}
  host:
    - lal >={{ lal_version }}
    - metaio >={{ metaio_version }}

outputs:
  - name: liblalmetaio
    script: install-lib.sh
    build:
      error_overdepending: true
      error_overlinking: true
      run_exports:
        - {{ pin_subpackage("liblalmetaio", max_pin="x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make  # [not win]
        - swig >={{ swig_version }}
      host:
        - liblal >={{ lal_version }}
        - metaio >={{ metaio_version }}
      run:
        - liblal >={{ lal_version }}
        - metaio >={{ metaio_version }}
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalmetaio/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm MetaIO Library
      description: |
        The LSC Algorithm MetaIO Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL MetaIO library.

  - name: python-lalmetaio
    script: install-python.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        # ignore run_exports from python's recipe
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config >=0.18.0
        - swig >={{ swig_version }}
      host:
        - {{ pin_subpackage('liblalmetaio', exact=True) }}
        - numpy
        - python
      run:
        - {{ pin_subpackage('liblalmetaio', exact=True) }}
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
    test:
      requires:
        - pytest >=4.0.0a0
      source_files:
        - test/python
      commands:
        - python -m pytest -rs -v test/python
      imports:
        - lalmetaio
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalmetaio/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm MetaIO Library
      description: |
        The LSC Algorithm MetaIO Library for gravitational wave data analysis.
        This package contains the python bindings.

  - name: lalmetaio
    script: install-bin.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - make
      host:
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalmetaio', exact=True) }}
        - python
      run:
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalmetaio', exact=True) }}
        - python
        - {{ pin_subpackage('python-lalmetaio', exact=True) }}
    test:
      commands:
        - lalmetaio_version --verbose
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalmetaio/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm MetaIO Library
      description: |
        The LSC Algorithm MetaIO Library for gravitational wave data analysis.

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalmetaio/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm MetaIO Library
  description: |
    The LSC Algorithm MetaIO Library for gravitational wave data analysis.

extra:
  feedstock-name: lalmetaio
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
