travis:
  secure:
    BINSTAR_TOKEN: hpl5S5xHSFMx4sm3AdhVZAN7Q6q8kSWuSummub/QXSrSjxhYhWRbkw3+yF+SwcUbJOou1ztqiQOrUHQvW4ODtFDL6fXsavQebY4XkJUX+8W8BE9+w0Vmg1t1x/25LrIt3kSZZryHsA9XAjkZWfdX0eCuVy/z5KBp3cAVTikheP1O3DOkEkd3xshQZ8IRLcSpIaqTNiaqMomgpmdF9Cz4joKoC1D10jyFi3mgJNaM90M8vaPushuaBGYkaCxznvnIsRWz4CARI8KR8j5Vv8cJigugS9+gaqEDRAa8+eKKRPFf7LKSMT0Fg2xCrODAIFeJ5g4afhTpSk8SBv0n7mGYCL0XXTETvJR5CEqY/sBGOSNT6peAgFerLwEsPewpO3etHIhUt/PfXVnFjV5YXP4VugceSm5x6iDYtJnlmGFHPntPZqKVvn5dWUpY4D+v8nRFcSqJGqCEDRP6jKfUoJb7wXyjepKRcBSvBBD+Jg4NXHWk9OXCNXj4M91OzCY34dUioozGeFsaqlfRCJ/JqPiTNnCon+MUU7kttRQ009NNRp8ZU0zrE+vpRf7PEera92eANBBz3lRN/xTOo+98FxSvLQHjbnFIDEbOQuVnNJAayd94Cta44bfDenZ5i6jogyrH6gdhucyEp/6Ul3DdE3rqVSupPclqC/eR+ufXx7ZuHmw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
